version: "3"

services:
  client:
    build: ./client
    container_name: react-ui
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      mern-network:

  backend:
    build: ./backend
    container_name: node-api
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - database
    networks:
      mern-network:

  database:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    networks:
      mern-network:

networks:
  mern-network:
    driver: bridge
