// Alert actions
export const DISPLAY_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";

// User register actions
export const USER_START_REGISTER = "USER_START_REGISTER";
export const USER_SUCCESS_REGISTER = "USER_SUCCESS_REGISTER";
export const USER_ERROR_REGISTER = "USER_ERROR_REGISTER";

// User login actions
export const USER_START_LOGIN = "USER_START_REGISTER";
export const USER_SUCCESS_LOGIN = "USER_SUCCESS_REGISTER";
export const USER_ERROR_LOGIN = "USER_ERROR_REGISTER";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_START_UPDATE = "USER_START_UPDATE";
export const USER_SUCCESS_UPDATE = "USER_SUCCESS_UPDATE";
export const USER_ERROR_UPDATE = "USER_ERROR_UPDATE";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_FORM_VALUES = "CLEAR_FORM_VALUES";

export const CODE_START_CREATE = "CODE_START_CREATE";
export const CODE_SUCCESS_CREATE = "CODE_SUCCESS_CREATE";
export const CODE_ERROR_CREATE = "CODE_ERROR_CREATE";

export const GET_CODES_START = "GET_CODES_START";
export const GET_CODES_SUCCESS = "GET_CODES_SUCCESS";

export const SET_EDIT_CODE = "SET_EDIT_CODE";
export const DELETE_CODE_START = "DELETE_CODE_START";

export const CODE_START_EDIT = "CODE_START_EDIT";
export const CODE_SUCCESS_EDIT = "CODE_SUCCESS_EDIT";
export const CODE_ERROR_EDIT = "CODE_ERROR_EDIT";

// get all codes from all users
// export const GET_ALL_CODES = "GET_ALL_CODES";
// export const GET_CODE_START = "GET_CODE_START";
